"""Add comite_id to fichiers

Revision ID: 08bc609c6593
Revises: d1352ea0c18b
Create Date: 2026-09-21 12:15:14.072561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bc609c6593'
down_revision: Union[str, Sequence[str], None] = 'd1352ea0c18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fichiers', sa.Column('comite_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'fichiers', 'comites', ['comite_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'fichiers', type_='foreignkey')
    op.drop_column('fichiers', 'comite_id')
    # ### end Alembic commands ###
