"""Make convention_id nullable in fichiers

Revision ID: 13fb21087f0f
Revises: 08bc609c6593
Create Date: 2026-09-21 12:21:55.482463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fb21087f0f'
down_revision: Union[str, Sequence[str], None] = '08bc609c6593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fichiers', 'convention_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fichiers', 'convention_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
