"""add signataire_um5 and articles fields

Revision ID: 360b9328a861
Revises: 63163b3d4dad
Create Date: 2026-08-03 18:53:47.133689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360b9328a861'
down_revision: Union[str, Sequence[str], None] = '63163b3d4dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conventions', sa.Column('signataire_um5', sa.String(), nullable=False))
    op.add_column('conventions', sa.Column('signataire_um5_autre', sa.String(), nullable=True))
    op.add_column('conventions', sa.Column('mots_cles', sa.JSON(), nullable=True))
    op.add_column('conventions', sa.Column('articles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conventions', 'articles')
    op.drop_column('conventions', 'mots_cles')
    op.drop_column('conventions', 'signataire_um5_autre')
    op.drop_column('conventions', 'signataire_um5')
    # ### end Alembic commands ###
