"""add articles_personnalisees colum

Revision ID: 508cb68738c5
Revises: 360b9328a861
Create Date: 2026-08-04 10:01:59.732523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508cb68738c5'
down_revision: Union[str, Sequence[str], None] = '360b9328a861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conventions', sa.Column('articles_personnalises', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conventions', 'articles_personnalises')
    # ### end Alembic commands ###
