"""create all tables

Revision ID: 63163b3d4dad
Revises: 
Create Date: 2026-07-06 12:59:04.658649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63163b3d4dad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('premiere_connexion', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_reference', sa.String(), nullable=False),
    sa.Column('intitule', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date_signature', sa.Date(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('mode_renouvellement', sa.String(), nullable=True),
    sa.Column('avec_budget', sa.Boolean(), nullable=True),
    sa.Column('validation_conseil', sa.Boolean(), nullable=True),
    sa.Column('formation_continue', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_reference')
    )
    op.create_table('alertes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_alerte', sa.String(), nullable=False),
    sa.Column('date_declenchement', sa.Date(), nullable=False),
    sa.Column('objet', sa.String(), nullable=True),
    sa.Column('envoyee', sa.Boolean(), nullable=True),
    sa.Column('traitee', sa.Boolean(), nullable=True),
    sa.Column('convention_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['convention_id'], ['conventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('modalites_paiement', sa.Text(), nullable=True),
    sa.Column('budget_recu', sa.String(), nullable=True),
    sa.Column('montant_depense', sa.Float(), nullable=True),
    sa.Column('reste_a_payer', sa.Float(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('convention_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['convention_id'], ['conventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('frequence', sa.String(), nullable=True),
    sa.Column('convention_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['convention_id'], ['conventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('convention_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['convention_id'], ['conventions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partenaires',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('pays', sa.String(), nullable=True),
    sa.Column('convention_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['convention_id'], ['conventions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerte_destinataires',
    sa.Column('alerte_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['alerte_id'], ['alertes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('comite_destinataires_externes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comite_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comite_id'], ['comites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comite_destinataires_internes',
    sa.Column('comite_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['comite_id'], ['comites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('reunions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_reunion', sa.Date(), nullable=False),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('comite_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comite_id'], ['comites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fichiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom_fichier', sa.String(), nullable=False),
    sa.Column('type_fichier', sa.String(), nullable=True),
    sa.Column('chemin', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('convention_id', sa.UUID(), nullable=True),
    sa.Column('reunion_id', sa.UUID(), nullable=True),
    sa.Column('budget_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['convention_id'], ['conventions.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reunions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fichiers')
    op.drop_table('reunions')
    op.drop_table('comite_destinataires_internes')
    op.drop_table('comite_destinataires_externes')
    op.drop_table('alerte_destinataires')
    op.drop_table('partenaires')
    op.drop_table('historique')
    op.drop_table('comites')
    op.drop_table('budgets')
    op.drop_table('alertes')
    op.drop_table('conventions')
    op.drop_table('users')
    # ### end Alembic commands ###
