"""add_duree_annees_to_conventions

Revision ID: 67779780e56c
Revises: 508cb68738c5
Create Date: 2026-08-07 01:02:27.729516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67779780e56c'
down_revision: Union[str, Sequence[str], None] = '508cb68738c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alertes', sa.Column('comite_id', sa.UUID(), nullable=True))
    op.add_column('alertes', sa.Column('reunion_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'alertes', 'comites', ['comite_id'], ['id'])
    op.create_foreign_key(None, 'alertes', 'reunions', ['reunion_id'], ['id'])
    op.add_column('conventions', sa.Column('duree_annees', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conventions', 'duree_annees')
    op.drop_constraint(None, 'alertes', type_='foreignkey')
    op.drop_constraint(None, 'alertes', type_='foreignkey')
    op.drop_column('alertes', 'reunion_id')
    op.drop_column('alertes', 'comite_id')
    # ### end Alembic commands ###
