"""ajouter_colonne_taille_fichiers

Revision ID: 9a707899ae03
Revises: d2e746cbee4c
Create Date: 2026-08-09 16:34:44.668136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a707899ae03'
down_revision: Union[str, Sequence[str], None] = 'd2e746cbee4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reunions')
    op.drop_table('comite_destinataires_internes')
    op.drop_table('comite_destinataires_externes')
    op.drop_constraint(op.f('alertes_reunion_id_fkey'), 'alertes', type_='foreignkey')
    op.drop_column('alertes', 'reunion_id')
    op.alter_column('comites', 'taches',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.add_column('fichiers', sa.Column('taille', sa.Integer(), nullable=True))
    op.alter_column('fichiers', 'chemin',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('fichiers_convention_id_fkey'), 'fichiers', type_='foreignkey')
    op.drop_constraint(op.f('fichiers_reunion_id_fkey'), 'fichiers', type_='foreignkey')
    op.drop_constraint(op.f('fichiers_budget_id_fkey'), 'fichiers', type_='foreignkey')
    op.create_foreign_key(None, 'fichiers', 'conventions', ['convention_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fichiers', 'budgets', ['budget_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fichiers', 'reunion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fichiers', sa.Column('reunion_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fichiers', type_='foreignkey')
    op.drop_constraint(None, 'fichiers', type_='foreignkey')
    op.create_foreign_key(op.f('fichiers_budget_id_fkey'), 'fichiers', 'budgets', ['budget_id'], ['id'])
    op.create_foreign_key(op.f('fichiers_reunion_id_fkey'), 'fichiers', 'reunions', ['reunion_id'], ['id'])
    op.create_foreign_key(op.f('fichiers_convention_id_fkey'), 'fichiers', 'conventions', ['convention_id'], ['id'])
    op.alter_column('fichiers', 'chemin',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('fichiers', 'taille')
    op.alter_column('comites', 'taches',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.add_column('alertes', sa.Column('reunion_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('alertes_reunion_id_fkey'), 'alertes', 'reunions', ['reunion_id'], ['id'])
    op.create_table('comite_destinataires_externes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comite_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comite_id'], ['comites.id'], name=op.f('comite_destinataires_externes_comite_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comite_destinataires_externes_pkey'))
    )
    op.create_table('comite_destinataires_internes',
    sa.Column('comite_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comite_id'], ['comites.id'], name=op.f('comite_destinataires_internes_comite_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('comite_destinataires_internes_user_id_fkey'))
    )
    op.create_table('reunions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_reunion', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('decisions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comite_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comite_id'], ['comites.id'], name=op.f('reunions_comite_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reunions_pkey'))
    )
    # ### end Alembic commands ###
