"""fix historique cascade to set null

Revision ID: bb4e78ace6c0
Revises: 9a707899ae03
Create Date: 2026-08-14 00:31:51.299903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb4e78ace6c0'
down_revision: Union[str, Sequence[str], None] = '9a707899ae03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alertes_convention_id_fkey'), 'alertes', type_='foreignkey')
    op.create_foreign_key(None, 'alertes', 'conventions', ['convention_id'], ['id'])
    op.drop_constraint(op.f('budgets_convention_id_fkey'), 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'conventions', ['convention_id'], ['id'])
    op.alter_column('comites', 'taches',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(op.f('comites_convention_id_fkey'), 'comites', type_='foreignkey')
    op.create_foreign_key(None, 'comites', 'conventions', ['convention_id'], ['id'])
    op.alter_column('fichiers', 'chemin',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('fichiers_budget_id_fkey'), 'fichiers', type_='foreignkey')
    op.create_foreign_key(None, 'fichiers', 'budgets', ['budget_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_historique_convention'), table_name='historique')
    op.drop_index(op.f('idx_historique_date'), table_name='historique')
    op.drop_index(op.f('idx_historique_user'), table_name='historique')
    op.drop_constraint(op.f('historique_user_id_fkey'), 'historique', type_='foreignkey')
    op.drop_constraint(op.f('historique_convention_id_fkey'), 'historique', type_='foreignkey')
    op.create_foreign_key(None, 'historique', 'conventions', ['convention_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'historique', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historique', type_='foreignkey')
    op.drop_constraint(None, 'historique', type_='foreignkey')
    op.create_foreign_key(op.f('historique_convention_id_fkey'), 'historique', 'conventions', ['convention_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('historique_user_id_fkey'), 'historique', 'users', ['user_id'], ['id'])
    op.create_index(op.f('idx_historique_user'), 'historique', ['user_id'], unique=False)
    op.create_index(op.f('idx_historique_date'), 'historique', [sa.literal_column('date_action DESC')], unique=False)
    op.create_index(op.f('idx_historique_convention'), 'historique', ['convention_id'], unique=False)
    op.drop_constraint(None, 'fichiers', type_='foreignkey')
    op.create_foreign_key(op.f('fichiers_budget_id_fkey'), 'fichiers', 'budgets', ['budget_id'], ['id'])
    op.alter_column('fichiers', 'chemin',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'comites', type_='foreignkey')
    op.create_foreign_key(op.f('comites_convention_id_fkey'), 'comites', 'conventions', ['convention_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comites', 'taches',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key(op.f('budgets_convention_id_fkey'), 'budgets', 'conventions', ['convention_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'alertes', type_='foreignkey')
    op.create_foreign_key(op.f('alertes_convention_id_fkey'), 'alertes', 'conventions', ['convention_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
