"""Add prenom, telephone, actif to users

Revision ID: d1352ea0c18b
Revises: b625ac3585c1
Create Date: 2026-09-19 22:26:54.268796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1352ea0c18b'
down_revision: Union[str, Sequence[str], None] = 'b625ac3585c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prenom', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('actif', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'actif')
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'prenom')
    # ### end Alembic commands ###
