"""add ondelete cascade to budget comite partenaire fichier alerte

Revision ID: ea316a52f7af
Revises: bb4e78ace6c0
Create Date: 2026-08-14 01:26:16.563540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea316a52f7af'
down_revision: Union[str, Sequence[str], None] = 'bb4e78ace6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alertes_convention_id_fkey'), 'alertes', type_='foreignkey')
    op.create_foreign_key(None, 'alertes', 'conventions', ['convention_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('budgets_convention_id_fkey'), 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'conventions', ['convention_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comites_convention_id_fkey'), 'comites', type_='foreignkey')
    op.create_foreign_key(None, 'comites', 'conventions', ['convention_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fichiers', 'convention_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fichiers', 'convention_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'comites', type_='foreignkey')
    op.create_foreign_key(op.f('comites_convention_id_fkey'), 'comites', 'conventions', ['convention_id'], ['id'])
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key(op.f('budgets_convention_id_fkey'), 'budgets', 'conventions', ['convention_id'], ['id'])
    op.drop_constraint(None, 'alertes', type_='foreignkey')
    op.create_foreign_key(op.f('alertes_convention_id_fkey'), 'alertes', 'conventions', ['convention_id'], ['id'])
    # ### end Alembic commands ###
